# Generated by Django 3.2.7 on 2021-09-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='describtion',
            field=models.CharField(default='blank', max_length=200),
            preserve_default=False,
        ),
    ]
