# Generated by Django 3.2.7 on 2021-09-24 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_describtion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='Name',
        ),
    ]
